### ISSUE TITLE
EtherCIS - Data Tidy Up - Ian to provide PostMan script to populate test data

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/Ripple-openEHR#6]
We are now building 2 scripts, one to be used on Marand, one on Ethercis. Same APIs just different data items so that they look vaguely sensible when the 2 sources are combined in Ripple UI.

Done so far

Problems
Procedures
Allergies
Lab results
Events

Next up

Contacts
Patient notes
Clinical notes
Orders
Medication
MDT
Vital signs

**Comment by PhilBarrett** [comment]
@freshehr please could I get an update on the remaining items? Cheers

**Comment by freshehr** [comment]
Complete and working on both CDRs

Problems
Procedures
Allergies
Lab results
Events
Contacts
Patient notes
Clinical notes
Orders
Medication
MDT
Vital signs
EoL Care Plans
Height Weight

Data displaying correctly at http://demo.rippleosi.org/#/patients/9999999068 

other than 
1. missing 'Type' for patient and clinical notes- suspect mismatch in QWED as the data is coming back ok
2. Medication - not displaying correctly due to updated template and implementation guide needs reworked in QEWD.
3. Lab orders - needed update to lab orders AQL which is now correct in the updated implementation guide.

**Comment by freshehr** [comment]
Can this be closed now?

**Comment by tony-shannon** [comment]
thanks Ian
Is this a script we can easily use to add test data ourselves? 
Do we need to help automate it further?
thanks
Tony

**Comment by freshehr** [comment]
Hi Tony,

Yes I was intending to share - I'll push the latest version of the repo that has the various postman artefacts an sample data.

Ian

**Comment by tony-shannon** [comment]
thanks Ian

Tony

**Comment by tony-shannon** [comment]
Going to redirect this to this related issue here;
https://github.com/ethercis/ethercis/issues/108
and at same time close this issue
